services:
  backend:
    build:
      context: backend
    restart: always
    ports:
      - "8080:8000"

  frontend:
    build:
      context: frontend
      args:
        - VITE_WS_URL=ws://localhost:8080
    restart: always
    ports:
      - "8000:80"
    environment:
      - VITE_WS_URL=ws://backend:8000
